// Generated by scripts/fit_compact_niche_flowers.py; indices match FlowerCatalog.
namespace Columbarium
{
    internal static class CompactNicheFlowerLayout
    {
        public const float MarginRatio = .025f;
        public const float RightSpillRatio = 0.20f;
        private static readonly float[] Ratios = { 1.285f, 0.980f, 0.890f, 0.865f, 0.855f, 1.025f, 0.855f, 0.825f, 0.795f, 0.845f, 0.845f, 0.910f };
        private static readonly float[] RightPaddings = { 0.20312500f, 0.09375000f, 0.06250000f, 0.03125000f, 0.04687500f, 0.10937500f, 0.04687500f, 0.03125000f, 0.03125000f, 0.04687500f, 0.03125000f, 0.07812500f };
        public static float RightPadding(int index)
        {
            if (index < 0 || index >= RightPaddings.Length) index = FlowerCatalog.DefaultIndex;
            return RightPaddings[index];
        }
        public static float SizeRatio(int index)
        {
            if (index < 0 || index >= Ratios.Length) index = FlowerCatalog.DefaultIndex;
            return Ratios[index];
        }
    }
}
