// Generated by scripts/prepare_thirtytwo.py from Art/32.png.
using UnityEngine;
namespace Columbarium
{
    internal static class ThirtyTwoLayout
    {
        public const float SourceWidth = 1774f;
        public const float SourceHeight = 887f;
        public const float CompactNorthOffset = 0.07380058f;
        public const float LargeNorthOffset = 0.11642261f;
        public const float FlowerMargin = .025f;
        public static readonly Rect[] Bounds = {
            new Rect(77f, 289f, 178f, 117f),
            new Rect(287f, 289f, 175f, 117f),
            new Rect(495f, 289f, 173f, 117f),
            new Rect(701f, 289f, 171f, 117f),
            new Rect(905f, 289f, 171f, 117f),
            new Rect(1109f, 289f, 174f, 117f),
            new Rect(1316f, 289f, 173f, 117f),
            new Rect(1523f, 289f, 175f, 117f),
            new Rect(77f, 406f, 178f, 112f),
            new Rect(287f, 406f, 175f, 112f),
            new Rect(495f, 406f, 173f, 112f),
            new Rect(701f, 406f, 171f, 112f),
            new Rect(905f, 406f, 171f, 112f),
            new Rect(1109f, 406f, 174f, 112f),
            new Rect(1316f, 406f, 173f, 112f),
            new Rect(1523f, 406f, 175f, 112f),
            new Rect(77f, 518f, 178f, 110f),
            new Rect(287f, 518f, 175f, 110f),
            new Rect(495f, 518f, 173f, 110f),
            new Rect(701f, 518f, 171f, 110f),
            new Rect(905f, 518f, 171f, 110f),
            new Rect(1109f, 518f, 174f, 110f),
            new Rect(1316f, 518f, 173f, 110f),
            new Rect(1523f, 518f, 175f, 110f),
            new Rect(77f, 628f, 178f, 113f),
            new Rect(287f, 628f, 175f, 113f),
            new Rect(495f, 628f, 173f, 113f),
            new Rect(701f, 628f, 171f, 113f),
            new Rect(905f, 628f, 171f, 113f),
            new Rect(1109f, 628f, 174f, 113f),
            new Rect(1316f, 628f, 173f, 113f),
            new Rect(1523f, 628f, 175f, 113f)
        };
        private static readonly float[] FlowerRatios = { 0.916f, 0.602f, 0.622f, 0.573f, 0.583f, 0.651f, 0.573f, 0.573f, 0.563f, 0.593f, 0.583f, 0.612f };
        private static readonly float[] RightPaddings = { 0.20312500f, 0.09375000f, 0.06250000f, 0.03125000f, 0.04687500f, 0.10937500f, 0.04687500f, 0.03125000f, 0.03125000f, 0.04687500f, 0.03125000f, 0.07812500f };
        private static int ValidIndex(int index) => index >= 0 && index < FlowerRatios.Length ? index : FlowerCatalog.DefaultIndex;
        public static float FlowerRatio(int index) => FlowerRatios[ValidIndex(index)];
        public static float RightPadding(int index) => RightPaddings[ValidIndex(index)];
    }
}
