"""Fit flowers for the standard eight-niche columbarium while preserving plaque text.

Run after changing the closed-door source, flower textures, or TallNicheBounds.
The generated C# ratios are also read by the preview renderer.
"""
from pathlib import Path
import json
import argparse
import re
import xml.etree.ElementTree as ET

import numpy as np
from PIL import Image
from niche_art import FRAME_SIZE, PLAQUE, INSCRIPTION

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('Melee', 'Shooting', 'Construction', 'Mining', 'Cooking', 'Plants',
         'Animals', 'Crafting', 'Artistic', 'Medicine', 'Social', 'Intellectual')
MARGIN = .025  # relative to door height; measured from the visible right edge
PLAQUE_LIMIT = .333
INSCRIPTION_LIMIT = .333
RIGHT_SPILL = .06  # slight overlap onto the niche's right support


def right_padding(source):
    mask = source.getchannel('A').point(lambda alpha: 255 if alpha >= 26 else 0)
    return (source.width - mask.getbbox()[2]) / source.width


def placement(width, height, ratio, padding=0):
    size = round(height * ratio)
    margin = round(height * MARGIN)
    return (width - size - margin + round(size * padding) + round(width * RIGHT_SPILL),
            height - size - margin, size)


def coverage(source, width, height, ratio):
    x, y, size = placement(width, height, ratio, right_padding(source))
    alpha = source.getchannel('A').resize((size, size), Image.Resampling.LANCZOS)
    canvas = Image.new('L', (width, height))
    canvas.paste(alpha, (x, y))
    pixels = np.asarray(canvas) >= 26  # count even faint edges conservatively
    fractions = []
    for l, t, r, b in (PLAQUE, INSCRIPTION):
        region = pixels[round(t / FRAME_SIZE[1] * height):round(b / FRAME_SIZE[1] * height),
                        round(l / FRAME_SIZE[0] * width):round(r / FRAME_SIZE[0] * width)]
        fractions.append(float(region.mean()))
    return fractions


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--keep-sizes', action='store_true', help='Reposition flowers without enlarging them again.')
    args = parser.parse_args()
    generated_path = ROOT / 'Source/Columbarium/NicheFlowerLayout.cs'
    previous_ratios = []
    if args.keep_sizes:
        previous = generated_path.read_text(encoding='utf-8').split('Ratios = {', 1)[1].split('}', 1)[0]
        previous_ratios = [float(v) for v in re.findall(r'([\d.]+)f', previous)]
    runtime = (ROOT / 'Source/Columbarium/Building_Columbarium.cs').read_text(encoding='utf-8')
    layout = runtime.split('Rect[] TallNicheBounds = {', 1)[1].split('};', 1)[0]
    bounds = [tuple(map(int, v)) for v in re.findall(
        r'new Rect\((\d+)f, (\d+)f, (\d+)f, (\d+)f\)', layout)]
    sizes = set()
    definitions = ET.parse(ROOT / 'Defs/ThingDefs/Columbarium_Things.xml').getroot()
    definition = next(d for d in definitions if d.findtext('defName') == 'ColumbariumModularTall')
    plane = tuple(map(float, definition.findtext('graphicData/drawSize').strip('()').split(',')))
    sx, sy = (round(v * 256) for v in plane)
    for x, y, w, h in bounds:
        sizes.add((round((x + w) / 1774 * sx) - round(x / 1774 * sx),
                   round((y + h) / 887 * sy) - round(y / 887 * sy)))
    report = {}
    sources = {}
    for index, name in enumerate(NAMES):
        source = Image.open(ROOT / f'Textures/Things/Flowers/{name}.png').convert('RGBA')
        steps = [round(previous_ratios[index] * 1000)] if args.keep_sizes else range(1300, 99, -1)
        for step in steps:
            ratio = step / 1000
            values = [coverage(source, w, h, ratio) for w, h in sizes]
            worst = np.max(values, axis=0)
            if worst[0] <= PLAQUE_LIMIT and worst[1] <= INSCRIPTION_LIMIT:
                report[name] = dict(ratio=ratio, right_padding=right_padding(source), plaque=float(worst[0]), inscription=float(worst[1]))
                break
        else:
            raise RuntimeError(f'No flower size fits: {name}')
    ratios = ', '.join(f'{report[n]["ratio"]:.3f}f' for n in NAMES)
    paddings = ', '.join(f'{report[n]["right_padding"]:.8f}f' for n in NAMES)
    generated = '''// Generated by scripts/fit_niche_flowers.py; indices match FlowerCatalog.
namespace Columbarium
{
    internal static class NicheFlowerLayout
    {
        public const float MarginRatio = .025f;
        public const float RightSpillRatio = SPILLf;
        private static readonly float[] Ratios = { RATIOS };
        private static readonly float[] RightPaddings = { PADDINGS };
        public static float RightPadding(int index)
        {
            if (index < 0 || index >= RightPaddings.Length) index = FlowerCatalog.DefaultIndex;
            return RightPaddings[index];
        }
        public static float SizeRatio(int index)
        {
            if (index < 0 || index >= Ratios.Length) index = FlowerCatalog.DefaultIndex;
            return Ratios[index];
        }
    }
}
'''.replace('RATIOS', ratios).replace('PADDINGS', paddings).replace('SPILL', f'{RIGHT_SPILL:.2f}')
    (ROOT / 'Source/Columbarium/NicheFlowerLayout.cs').write_text(generated, encoding='utf-8')
    (ROOT / 'Preview/flower_coverage.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
