"""Enlarge flowers for the compact eight-niche columbarium only."""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET

import numpy as np
from PIL import Image
from niche_art import COMPACT_FRAME_SIZE, COMPACT_PLAQUE, COMPACT_INSCRIPTION

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('Melee', 'Shooting', 'Construction', 'Mining', 'Cooking', 'Plants',
         'Animals', 'Crafting', 'Artistic', 'Medicine', 'Social', 'Intellectual')
PLAQUE_LIMIT = .50
INSCRIPTION_LIMIT = .50
RIGHT_SPILL = .20  # fraction of one niche width beyond its right frame
MARGIN = .025       # keep the lower edge clear of the frame


def visible_right_padding(source):
    alpha = source.getchannel('A').point(lambda a: 255 if a >= 26 else 0)
    return (source.width - alpha.getbbox()[2]) / source.width


def measure(source, width, height, ratio, right_padding):
    size = round(height * ratio)
    margin = round(height * MARGIN)
    x = width - size - margin + round(size * right_padding) + round(width * RIGHT_SPILL)
    y = height - size - margin
    alpha = source.getchannel('A').resize((size, size), Image.Resampling.LANCZOS)
    canvas = Image.new('L', (width, height))
    canvas.paste(alpha, (x, y))
    pixels = np.asarray(canvas) >= 26
    fractions = []
    for left, top, right, bottom in (COMPACT_PLAQUE, COMPACT_INSCRIPTION):
        box = pixels[round(top / COMPACT_FRAME_SIZE[1] * height):round(bottom / COMPACT_FRAME_SIZE[1] * height),
                     round(left / COMPACT_FRAME_SIZE[0] * width):round(right / COMPACT_FRAME_SIZE[0] * width)]
        fractions.append(float(box.mean()))
    return fractions


def main():
    definitions = ET.parse(ROOT / 'Defs/ThingDefs/Columbarium_Things.xml').getroot()
    compact = next(d for d in definitions if d.findtext('defName') == 'ColumbariumModularCompactTall')
    plane = tuple(map(float, compact.findtext('graphicData/drawSize').strip('()').split(',')))
    runtime = (ROOT / 'Source/Columbarium/Building_Columbarium.cs').read_text(encoding='utf-8')
    layout = runtime.split('Rect[] TallNicheBounds = {', 1)[1].split('};', 1)[0]
    bounds = [tuple(map(int, values)) for values in re.findall(
        r'new Rect\((\d+)f, (\d+)f, (\d+)f, (\d+)f\)', layout)]
    plane_width, plane_height = (round(v * 256) for v in plane)
    door_sizes = []
    for x, y, w, h in bounds:
        door_sizes.append((round((x + w) / 1774 * plane_width) - round(x / 1774 * plane_width),
                           round((y + h) / 887 * plane_height) - round(y / 887 * plane_height)))

    ratios, paddings, report = [], [], {}
    for name in NAMES:
        flower = Image.open(ROOT / f'Textures/Things/Flowers/{name}.png').convert('RGBA')
        padding = visible_right_padding(flower)
        for step in range(2000, 99, -5):
            ratio = step / 1000
            coverages = [measure(flower, w, h, ratio, padding) for w, h in door_sizes]
            worst = np.max(coverages, axis=0)
            if worst[0] <= PLAQUE_LIMIT and worst[1] <= INSCRIPTION_LIMIT:
                ratios.append(ratio)
                paddings.append(padding)
                report[name] = dict(ratio=ratio, plaque_region_coverage=float(worst[0]),
                                    inscription_region_coverage=float(worst[1]), right_spill_fraction=RIGHT_SPILL)
                break
        else:
            raise RuntimeError(f'Could not fit {name} within compact limits')

    generated = '''// Generated by scripts/fit_compact_niche_flowers.py; indices match FlowerCatalog.
namespace Columbarium
{
    internal static class CompactNicheFlowerLayout
    {
        public const float MarginRatio = .025f;
        public const float RightSpillRatio = SPILLf;
        private static readonly float[] Ratios = { RATIOS };
        private static readonly float[] RightPaddings = { PADDINGS };
        public static float RightPadding(int index)
        {
            if (index < 0 || index >= RightPaddings.Length) index = FlowerCatalog.DefaultIndex;
            return RightPaddings[index];
        }
        public static float SizeRatio(int index)
        {
            if (index < 0 || index >= Ratios.Length) index = FlowerCatalog.DefaultIndex;
            return Ratios[index];
        }
    }
}
'''.replace('RATIOS', ', '.join(f'{v:.3f}f' for v in ratios)).replace(
    'PADDINGS', ', '.join(f'{v:.8f}f' for v in paddings)).replace(
    'SPILL', f'{RIGHT_SPILL:.2f}')
    (ROOT / 'Source/Columbarium/CompactNicheFlowerLayout.cs').write_text(generated, encoding='utf-8')
    (ROOT / 'Preview/compact_flower_coverage.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
