"""Fit enlarged flowers for the compact 32-niche columbarium only."""
from pathlib import Path
import json

import numpy as np
from PIL import Image
from fit_compact_niche_flowers import (
    INSCRIPTION_LIMIT, MARGIN, NAMES, PLAQUE_LIMIT, RIGHT_SPILL,
    measure, visible_right_padding,
)

ROOT = Path(__file__).resolve().parents[1]
SOURCE_WIDTH, SOURCE_HEIGHT = 1774, 887
SCALE = 256


def main():
    layout_source = (ROOT / 'Source/Columbarium/ThirtyTwoLayout.cs').read_text(encoding='utf-8')
    section = layout_source.split('Rect[] Bounds = {', 1)[1].split('};', 1)[0]
    import re
    bounds = [tuple(map(float, values)) for values in re.findall(
        r'new Rect\(([\d.]+)f, ([\d.]+)f, ([\d.]+)f, ([\d.]+)f\)', section)]
    definition = ROOT / 'Defs/ThingDefs/Columbarium_32.xml'
    import xml.etree.ElementTree as ET
    defs = ET.parse(definition).getroot()
    compact = next(d for d in defs if d.findtext('defName') == 'ColumbariumThirtyTwoCompact')
    plane = tuple(map(float, compact.findtext('graphicData/drawSize').strip('()').split(',')))
    plane_width, plane_height = (round(v * SCALE) for v in plane)
    door_sizes = [(round((x+w)/SOURCE_WIDTH*plane_width)-round(x/SOURCE_WIDTH*plane_width),
                   round((y+h)/SOURCE_HEIGHT*plane_height)-round(y/SOURCE_HEIGHT*plane_height))
                  for x,y,w,h in bounds]

    ratios, paddings, report = [], [], {}
    for name in NAMES:
        flower = Image.open(ROOT / f'Textures/Things/Flowers/{name}.png').convert('RGBA')
        padding = visible_right_padding(flower)
        for step in range(2000, 99, -5):
            ratio = step / 1000
            coverages = [measure(flower, w, h, ratio, padding) for w,h in door_sizes]
            worst = np.max(coverages, axis=0)
            if worst[0] <= PLAQUE_LIMIT and worst[1] <= INSCRIPTION_LIMIT:
                ratios.append(ratio)
                paddings.append(padding)
                report[name] = dict(ratio=ratio, plaque_region_coverage=float(worst[0]),
                                    inscription_region_coverage=float(worst[1]),
                                    right_spill_fraction=RIGHT_SPILL)
                break
        else:
            raise RuntimeError(f'Could not fit {name} within compact limits')

    generated = '''// Generated by scripts/fit_compact_thirtytwo_flowers.py; indices match FlowerCatalog.
namespace Columbarium
{
    internal static class CompactThirtyTwoFlowerLayout
    {
        public const float MarginRatio = .025f;
        public const float RightSpillRatio = SPILLf;
        private static readonly float[] Ratios = { RATIOS };
        private static readonly float[] RightPaddings = { PADDINGS };
        public static float RightPadding(int index)
        {
            if (index < 0 || index >= RightPaddings.Length) index = FlowerCatalog.DefaultIndex;
            return RightPaddings[index];
        }
        public static float SizeRatio(int index)
        {
            if (index < 0 || index >= Ratios.Length) index = FlowerCatalog.DefaultIndex;
            return Ratios[index];
        }
    }
}
'''.replace('RATIOS', ', '.join(f'{v:.3f}f' for v in ratios)).replace(
        'PADDINGS', ', '.join(f'{v:.8f}f' for v in paddings)).replace(
        'SPILL', f'{RIGHT_SPILL:.2f}')
    (ROOT / 'Source/Columbarium/CompactThirtyTwoFlowerLayout.cs').write_text(generated, encoding='utf-8')
    (ROOT / 'Preview/compact_thirtytwo_flower_coverage.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
